version: "3"
services:

  model_ecaas_agrifieldnet_gold_v1:
    image: radiantearth/model_ecaas_agrifieldnet_gold:1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app,cached
